# commit to be tagged for the new release
commit = "HEAD"

project_name = "terraform-provider-talos"
github_repo = "siderolabs/terraform-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.0-alpha.11"
pre_release = true

[notes]

    [notes.updates]
        title = "Fixes"
        description = """\
Fixed an issue with the provider when using a secure Talos client.
"""
