# commit to be tagged for the new release
commit = "HEAD"

project_name = "terraform-provider-talos"
github_repo = "siderolabs/terraform-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.5.0"
pre_release = true

[notes]

    [notes.talos_machine_secrets]
        title = "Talos Machine Secrets"
        description = """\
`talos_machine_secrets` resource now regenerates client config when the time to expiry is less than a month.
"""

    [notes.talos_cluster_health]
        title = "Talos Cluster Health"
        description = """\
`talos_cluster_health` data source now has a way to skip running the Kubernetes components health check by setting `skip_kubernetes_checks` to `true`.
"""

    [notes.updates]
        title = "Component Updates"
        description = """\
Talos sdk: v1.8.0-alpha.0
"""
